Update Digital Ocean program status
malgamves/CommunityWriterPrograms pull request #41
Opened 2020-10-23 05:26 UTC by krissnawat

![image](https://user-images.githubusercontent.com/26294749/96959755-fb11f580-152a-11eb-979d-9ce094905a5e.png)

2020-11-23 21:36 UTC, malgamves requested changes

2020-11-23 21:36 UTC, malgamves commented on README.md
> +- [Digital Ocean](https://www.digitalocean.com/write-for-donations/) - Up to $400 per piece ****Currently paused accept new writer**
Hey @krissnawat thanks for the addition. Could you change the text to 

`** *Applications currently on hold**`

2021-01-09 18:56 UTC, LindaOjo reviewed
I noticed this is a bit delayed, so I went ahead to make the change.

2021-01-09 18:56 UTC, LindaOjo commented on README.md
> +- [Digital Ocean](https://www.digitalocean.com/write-for-donations/) - Up to $400 per piece ****Currently paused accept new writer**
```suggestion
- [Digital Ocean](https://www.digitalocean.com/write-for-donations/) - Up to $400 per piece **Applications currently on hold**
```

2021-01-21 22:33 UTC, malgamves commented
Thanks @LindaOjo - merging 🚀

2021-01-21 22:34 UTC, merged